apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
...
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        volumes:
        - name: wordpress-volume
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
