apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress  # Matches the label in the Deployment
  ports:
    - protocol: TCP
      port: 80  # Service port (exposed externally)
      targetPort: 80  # Target port of the WordPress container
