apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest  # Replace with your desired version
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin  # Replace with a strong password
          - name: MYSQL_DATABASE
            value: wordpress-db  # Replace with your desired database name
        ports:
          - containerPort: 3306
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
